FirstTask
z-h-z-h/laravel-labware-catalog pull request #3
Opened 2020-10-30 18:53 UTC by AlexSeeer

2020-10-31 12:19 UTC, z-h-z-h commented on app/Models/Company.php
> +    protected $fillable =['slug','title','description'];
- после = должен быть пробел
- каждый элемент массива должен быть на новой строке

2020-10-31 12:19 UTC, z-h-z-h commented on app/Models/Category.php
> +        return $this()->belongsTo('App\Company');
это неправильно и работать не будет

2020-10-31 12:21 UTC, z-h-z-h commented on app/Models/Company.php
> +    public function sets()
```suggestion
    public function sets(): HasMany
```

2020-10-31 12:21 UTC, z-h-z-h commented on app/Models/Company.php
> +        return $this->hasMany('App\set');
ошибка, set с маленькой буквы

2020-10-31 12:22 UTC, z-h-z-h commented on app/Models/Company.php
> +    public function sets()
Для всех методов описывающих отношения необходимо добавить тип как в примере

2020-10-31 12:24 UTC, z-h-z-h requested changes

2020-10-31 12:24 UTC, z-h-z-h commented on app/Models/Set.php
> +    protected $fillable = ['slug', 'title', 'description', 'category_id', 'company_id'];
разбить массив на несколько строк

2020-10-31 12:24 UTC, z-h-z-h commented on README.md
> +333333333
убери это

2020-10-31 20:46 UTC, AlexSeeer commented on app/Models/Category.php
> +        return $this()->belongsTo('App\Company');
ебать, как я вообще умудрился туда эти скобки воткнуть

2020-10-31 20:49 UTC, AlexSeeer commented on app/Models/Company.php
> +    public function sets()
А что это нам дает?

2020-10-31 21:11 UTC, merged

2020-11-01 09:43 UTC, z-h-z-h commented on app/Models/Category.php
> +    public function company(): belongsTo
что такое belongsTo? это не рабочий код, так как нет такого класса или типа
метод company возвращает объект класса Illuminate\Database\Eloquent\Relations\BelongsTo
нужно правильно указать тип возвращаемого значения в методах отношений во всех моделях.

2020-11-01 09:43 UTC, z-h-z-h commented on app/Models/Category.php
> +namespace App;
тут и в остальных моделях неправильно, у тебя модели лежат в папке app/Models, а нэймспейс указан как App, это не рабочий код.
namespace App/Models; будет правильно.